# Generated by Django 3.1.4 on 2021-01-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cr_dr',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
